# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [35]:
# a =
a=pd.Series([100,200,300,400])

Print a, and data type

In [36]:
print(a)
type(a)

0    100
1    200
2    300
3    400
dtype: int64

pandas.core.series.Series

Using indexing access the element 300 from the series a.

In [7]:
element=a[2]
print(element)

300

What are the values of index for series a?

In [37]:
index=a.index
print(index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [38]:

a.index=['c','a','b','d']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [10]:
value=a['d']
print(value)

400

Sort the values wrt to the index and print it

In [11]:
sorted_a=a.sort_index()
print(sorted_a)

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [39]:
# b =
b=pd.Series([800,450,100],index=['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [40]:
# a =

a=pd.concat([a,b])

In [18]:
#print a again after appending b into it

print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [19]:
# a =
a=a.sort_values(ascending=False)
print(a)

e    800
e    800
f    450
f    450
d    400
b    300
a    200
c    100
g    100
g    100
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [41]:
# df =
df=pd.DataFrame(a)
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [42]:
shape=df.shape
print(shape)

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [43]:
# yep its same as the series.
print(df.index)

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [44]:

head=df.head()
print(head)

     0
c  100
a  200
b  300
d  400
e  800

In [45]:
tail=df.tail()
print(tail)

     0
b  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [46]:
df.columns=['points']
print(df)

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [47]:
#Create fruits array

# fruits =
fruits=np.random.choice(['orange','mango','apple'],size=7)
print(fruits)

['mango' 'orange' 'apple' 'apple' 'apple' 'apple' 'apple']

In [51]:
#Create series fruits out of fruits array

# fruits =

fruits=pd.Series(fruits)
print(fruits)

0     mango
1    orange
2     apple
3     apple
4     apple
5     apple
6     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [52]:
new_index=df.index
fruits.index=new_index
print(fruits)

c     mango
a    orange
b     apple
d     apple
e     apple
f     apple
g     apple
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [55]:
df['fruits'] = fruits


print(df.head())

   points  fruits
c     100   mango
a     200  orange
b     300   apple
d     400   apple
e     800   apple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [57]:
# d1 =
d1=pd.DataFrame({'city':['Chandigarh','Delhi','Kanpur','Chennai','Manali'],'Temperature':[15,22,20,26,-2]})

Print(d1)

In [58]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [59]:
d1.shape

(5, 2)

Set city = d1['city']

In [60]:
city=d1['city']
print(city)

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object

print city <br>
What is the type of city.

In [61]:

type(city)

pandas.core.series.Series

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [62]:
# d2 =

d2=pd.DataFrame({'city':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],'Temperature':[24,35,36,39]})

print the shape of this dataframe

In [63]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [65]:
# d3 =
d3=pd.concat([d1,d2])

print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [66]:
citys=d3[d3['Temperature']<=20]
print(citys)

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [68]:

d3[d3['Temperature']>=35]

          city  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [71]:
# write function here

# def is_ut(x):

#     # write code below

# d3['is_ut'] =

def is_ut(city):
    union_territories = ['Chandigarh', 'Pondicherry', 'Delhi']
    return city in union_territories

d3['is_ut'] = d3['city'].apply(is_ut)

In [72]:
# print d3

d3

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [74]:
# write function here
def c_to_f(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

In [75]:
# check function c_to_f(10)

c_to_f(10)

50.0

In [78]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['temp_farenhiet']=d3['Temperature'].apply(c_to_f)
d3

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
0    Bengalaru           24  False            75.2
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [79]:

subset=d3[d3['is_ut']==True]
print(subset)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
3  Pondicherry           39   True           102.2

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [80]:

subset2=d3[d3['temp_farenhiet']>90]
print(subset2)

          city  Temperature  is_ut  temp_farenhiet
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

Select only the first three rows of the dataframe d1.

In [81]:
d1.head(3)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [82]:
subset_last_cols = d1.iloc[:, -2:]
print(subset_last_cols)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

## Groupby

In [86]:
# Create a dataframe using dictionary of your choice

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'mark': [25, 30, 35, 40, 45],
        'subject': ['sub1','sub1', 'sub2', 'sub3', 'sub3']}

df = pd.DataFrame(data)
print(df)

      Name  mark subject
0    Alice    25    sub1
1      Bob    30    sub1
2  Charlie    35    sub2
3    David    40    sub3
4      Eve    45    sub3

In [87]:
# Use Groupby of single column with aggregate sum()

pd.DataFrame(df.groupby('subject')['mark'].sum())

         mark
subject
sub1       55
sub2       35
sub3       85

In [88]:
# Use Groupby of single column with aggregate count()

pd.DataFrame(df.groupby('subject')['mark'].count())

         mark
subject
sub1        2
sub2        1
sub3        2

In [89]:
# Use Groupby of single column with aggregate min() and max()

pd.DataFrame(df.groupby('subject')['mark'].agg(['min','max']))

         min  max
subject
sub1      25   30
sub2      35   35
sub3      40   45

In [90]:
# Use Groupby of any 2 columns with aggregate mean()

pd.DataFrame(df.groupby(['subject','Name'])['mark'].mean())

                 mark
subject Name
sub1    Alice    25.0
        Bob      30.0
sub2    Charlie  35.0
sub3    David    40.0
        Eve      45.0

In [91]:
# Use Groupby of any 2 columns with aggregate min() and max()


pd.DataFrame(df.groupby(['subject','Name'])['mark'].agg(['min','max']))

                 min  max
subject Name
sub1    Alice     25   25
        Bob       30   30
sub2    Charlie   35   35
sub3    David     40   40
        Eve       45   45

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [93]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [95]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [96]:
len(a)

457

What is the type of a?

In [97]:

type(a)

pandas.core.indexes.datetimes.DatetimeIndex